files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/strings.xml
  - source: /app/src/main/res/values/cynk_strings.xml
    translation: /app/src/main/res/values-%android_code%/cynk_strings.xml
